### ISSUE TITLE
Unhandled rejection HeadlessError

### ISSUE THREAD

**Issue by mato75** [baudehlo/node-phantom-simple#107]
Unhandled rejection HeadlessError: Request() error evaluating open() call: Error: socket hang up
    at ClientRequest.<anonymous> (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:502:18)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnEnd (_http_client.js:300:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)

**Comment by mato75** [comment]
Hm, found the issue. In some cases I killed phantomjs instance before actions were finished.
