### ISSUE TITLE
When Phantom Process died it stops NodeJS process

### ISSUE THREAD

**Issue by mato75** [baudehlo/node-phantom-simple#110]
I am trying to wrap this error with bluebird promise, but what ever I do, this still is logged and it breaks NodeJS process, so that I have to restart it. Any suggestions?          

    Unhandled rejection HeadlessError: Phantom Process died
    at poll_func (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:586:10)
    at /vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:54:7
    at ClientRequest.<anonymous> (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:499:11)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:262:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

**Comment by mato75** [comment]
I tried putting try catch around it, it does not help.
