### ISSUE TITLE
Error runing in openshift

### ISSUE THREAD

**Issue by arbh89** [baudehlo/node-phantom-simple#125]
Hi,

I am trying to run phanton with node in openshift but i am gettng the next error.

Unhandled rejection HeadlessError: Unexpected output from PhantomJS: Ready [252552] []
    at Socket.<anonymous> (/node_modules/node-phantom-simple/node-phantom-simple.js:169:18)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at Pipe.onread (net.js:529:21)

**Comment by puzrin** [comment]
All such kind of errors are caused by kludges to detect phantomjs port by pid. May be your openshift image does not have some cli commands or have outdated versions. I'd suggest to try this things:

- Add necessary utils (usually, ss / netstat)
- Send PR with fixes for openshift
- Switch to slimerjs because it get port right without those kludges (but it slower and need xfvb, see travis config).

**Comment by creativefull** [comment]
+1

**Comment by spalger** [comment]
Just saw this too, exact same error messages (different PID though).

Looks like the issue is this RegExp: https://github.com/baudehlo/node-phantom-simple/blob/ecf7743c0733f0713dba5b684c158cf02877ef24/node-phantom-simple.js#L165

If it was adjusted to support the `[]` at the end then it would be able to fall back and detect the phantom port with the cli tools @puzrin mentioned.
