### ISSUE TITLE
It doesnt work with SlimerJS

### ISSUE THREAD

**Issue by mato75** [baudehlo/node-phantom-simple#127]
I am getting this issue.	

return browser.createPage(function (err, page) {
	              ^

TypeError: Cannot read property 'createPage' of undefined
    at /vagrant/server/tests/phantomjs/events2.js:9:16
    at /vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:283:7
    at ChildProcess.immediateExit (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:155:14)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)

**Comment by puzrin** [comment]
https://github.com/baudehlo/node-phantom-simple/blob/master/package.json#L18

it works

**Comment by mato75** [comment]
This is the code and I am running it with node test.js. What could be the problem here?

````
var driver = require('node-phantom-simple');
driver.create({
	path: require('slimerjs').path,
}, function(err, browser) {
	return browser.createPage(function (err, page) {
		page.onConsoleMessage = function(msg) {
			console.log('CONSOLE: ' + msg);
		};
		setTimeout(function() {
			page.open('url', function(err, status) {
				console.log('opened', status);
			});
		}, 1000);

	});
});
````

**Comment by mato75** [comment]
With which slimerJS version is node-phantom-simple compatible?

**Comment by puzrin** [comment]
https://github.com/baudehlo/node-phantom-simple/blob/master/package.json#L25 0.9.6 and up.

**Comment by mato75** [comment]
Hm. I am using 0.9.6, but with no luck.

**Comment by puzrin** [comment]
@mato75, please, always specify details in your reports, and check existing tests first. That's not a twitter :)

**Comment by mato75** [comment]
Running npm run test-slimer

````
vagrant@vagrant:~/test/node_modules/node-phantom-simple$ npm run test-slimer

> node-phantom-simple@2.2.4 test-slimer /home/vagrant/test/node_modules/node-phantom-simple
> ENGINE=slimerjs ./node_modules/.bin/mocha

/home/vagrant/test/node_modules/node-phantom-simple/node_modules/mocha/lib/utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) 'test'
    at Object.lookupFiles (/home/vagrant/test/node_modules/node-phantom-simple/node_modules/mocha/lib/utils.js:628:15)
    at /home/vagrant/test/node_modules/node-phantom-simple/node_modules/mocha/bin/_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (/home/vagrant/test/node_modules/node-phantom-simple/node_modules/mocha/bin/_mocha:325:6)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3

````

**Comment by puzrin** [comment]
```sh
git clone https://github.com/baudehlo/node-phantom-simple.git
cd node-phantom-simple
npm install
npm run test-slimer
```

How did you installed that? What is your OS & node version? Your stack trace shows problem to be in mocha, not here

**Comment by mato75** [comment]
I tried before from node_modules/node-phantom-simple, but now I used you suggestion and I get this:

npm run test-slimer

> node-phantom-simple@2.2.4 test-slimer /home/vagrant/test/node-phantom-simple
> ENGINE=slimerjs ./node_modules/.bin/mocha



  bad path
    ✓ bad path produces an error
Deprecated 'phantomPath' option - use 'path' instead
    ✓ deprecated path name still should be ok

  command line options
    1) load-images is default
    2) load-images is true
    3) load-images is false

  engine.create()
    ✓ without options (471ms)
    4) callback is last
Deprecated '.create(callback, options)' syntax - use '.create(options, callback)' instead
    5) callback is first (legacy style)

  page
    6) set get hierarchical

  engine
    7) injectjs
    8) should return false on non-existent file

  engine
    9) unexpected exit

  page
    10) create

  page.evaluate()
    11) should return false as boolean (#43)
    12) without extra args
    13) with extra args, callback is last
    14) with extra args (legacy style)

  page
    15) includeJs

  page
    16) open

  push notifications
    ✓ onConsoleMessage (387ms)
    ✓ onCallback (440ms)
    ✓ onError (444ms)
    ✓ onUrlChanged (404ms)
    ✓ onLoadStarted (434ms)
    ✓ onLoadFinished (606ms)
    ✓ onResourceReceived (449ms)

  page
    17) release

  page
    18) render to binary & base64

  page
    19) send event

  page
    20) setFn

  page
    21) set get

  page
    22) set get hierarchical

  page
    23) uploadFile

  page.waitForSelector()
    24) callback is last
    25) callback without timeout
    26) callback before timeout (legacy style)


  10 passing (6s)
  26 failing

  1) command line options load-images is default:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  2) command line options load-images is true:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  3) command line options load-images is false:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  4) engine.create() callback is last:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  5) engine.create() callback is first (legacy style):
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  6) page set get hierarchical:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  7) engine injectjs:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  8) engine should return false on non-existent file:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  9) engine unexpected exit:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  10) page create:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  11) page.evaluate() should return false as boolean (#43):
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  12) page.evaluate() without extra args:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  13) page.evaluate() with extra args, callback is last:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  14) page.evaluate() with extra args (legacy style):
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  15) page includeJs:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  16) page open:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  17) page release:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  18) page render to binary & base64:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  19) page send event:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  20) page setFn:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  21) page set get:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  22) page set get hierarchical:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  23) page uploadFile:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  24) page.waitForSelector() callback is last:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  25) page.waitForSelector() callback without timeout:
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

  26) page.waitForSelector() callback before timeout (legacy style):
     HeadlessError: Phantom immediately exited with: 255
      at ChildProcess.immediateExit (node-phantom-simple.js:153:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)




npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test-slimer"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! node-phantom-simple@2.2.4 test-slimer: `ENGINE=slimerjs ./node_modules/.bin/mocha`
npm ERR! Exit status 26
npm ERR!
npm ERR! Failed at the node-phantom-simple@2.2.4 test-slimer script 'ENGINE=slimerjs ./node_modules/.bin/mocha'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-phantom-simple package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ENGINE=slimerjs ./node_modules/.bin/mocha
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-phantom-simple
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/test/node-phantom-simple/npm-debug.log

**Comment by puzrin** [comment]
You did not replied about node version & your OS.

**Comment by mato75** [comment]
npm -v
3.3.12
node -v
v5.4.1
uname -a
Linux vagrant 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u6 x86_64 GNU/Linux

**Comment by puzrin** [comment]
I don't know restrictions of your virtual env. I think it worth to search in google for specifics. For example, travis requies aditional setup because slimerjs is NOT headless https://github.com/baudehlo/node-phantom-simple/blob/master/.travis.yml#L7
