### ISSUE TITLE
Missing support for `customHeaders`

### ISSUE THREAD

**Issue by cvan** [baudehlo/node-phantom-simple#35]
```js
var phantom = require('node-phantom-simple');

var url = 'http://google.com/';

phantom.create(function (err, ph) {
  return ph.createPage(function (err, page) {
    page.address = url;
    page.customHeaders({
      'Cache-Control': 'no-cache',
      'Pragma': 'no-cache'
    });

    return page.open(url, function (err, status) {
      console.log('Status', status);
    });
  });
});
```

```bash
%% node test.js
TypeError: Object #<Object> has no method 'customHeaders'
    at /opt/phantomHAR/test.js:9:10
    at /opt/phantomHAR/node_modules/node-phantom-simple/node-phantom-simple.js:40:26
    at IncomingMessage.<anonymous> (/opt/phantomHAR/node_modules/node-phantom-simple/node-phantom-simple.js:455:17)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at _stream_readable.js:895:16
    at process._tickCallback (node.js:339:11)
```

**Comment by puzrin** [comment]
http://phantomjs.org/api/webpage/property/custom-headers.html

`customHaders` is property, not function. Juse use `page.set('customHades', obj)`, and be happy! See [example](https://github.com/nodeca/navit/blob/master/lib/do.js#L74), this code works without problems.
