### ISSUE TITLE
HeadlessError: Phantom Process died

### ISSUE THREAD

**Issue by coffy** [baudehlo/node-phantom-simple#92]
Hi,
i am trying to generate pdf from html with node-phantom-simple;

    var phantom         = require('node-phantom-simple');
    phantom.create(options, function (err, phantomSession) 

gets session successfully, although 
    
    phantomSession.process.connected
is false

then immediately in node-phantom-simple.js following is executed on line 568:

    phantom.once('exit', function () {
      dead = true;
    }); 

which returns error: 

    Request() error evaluating createPage() call: Error: connect ECONNREFUSED
    HeadlessError: Phantom Process died
    at poll_func (.../node_modules/node-phantom-simple/node-phantom-simple.js:573:10)
    at copy (.../node_modules/node-phantom-simple/node-phantom-simple.js:47:7)
    at ClientRequest.exports.create.JSON.stringify.page (.../node_modules/node-phantom-simple/node-phantom-simple.js:493:9)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket._destroy.self.errorEmitted (net.js:441:14)
    at process._tickDomainCallback (node.js:459:13)

Can you help with this issue? 'phantomjs' is executable  from command line

i am on mac os (El Capitan) and running nodejs from Webstorm

**Comment by puzrin** [comment]
Please provide a minimal working example, which can be reproduced

**Comment by puzrin** [comment]
Closing - timed out.
